name: Cypress Tests
on: [push]
jobs:
  cypress-run:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.5.0
      - name: Set up Python 3.10.4
        uses: actions/setup-python@v2
        with:
          python-version: 3.10.4
      - name: Install backend dependencies
        run: |
          python -m pip install --upgrade pip
          pip3 install uvicorn
          pip3 install fastapi
          pip3 install supabase
          pip3 install pyyaml
      - name: Run uvicorn server in background
        run: |
          export SUPABASE_URL="${{ secrets.SUPABASE_URL }}"
          export SUPABASE_KEY="${{ secrets.SUPABASE_KEY }}"
          python3 -m uvicorn backend.main:app &
      - name: Run Unit tests
        run: pytest
      - name: Setup Node.js environment
        uses: actions/setup-node@v3.5.1
        with:
          node-version: 16.17.0
      - name: Build, run and test Svelte app
        run: |
          npm install cypress
          cd frontend/app
          npm install
          npm run dev &
          npm config list
          npm config ls -l
          until $(curl --output /dev/null --silent --head --fail http://localhost:8080)
          do
          printf "."
          sleep 1
          done
          cd ..
          cd ..
          cypress run

