name: Cypress Tests
on: [push]
jobs:
  cypress-run:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.5.0
      - name: Set up Python 3.10.4
        uses: actions/setup-python@v2
        with:
          python-version: 3.10.4
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip3 install uvicorn
          pip3 install fastapi
          pip3 install supabase
          pip3 install pyyaml
      - name: Run server in background
        run: python3 -m uvicorn backend.main:app &
      - name: Setup Node.js environment
        uses: actions/setup-node@v3.5.1
      - name: Build and run Svelte app
        run: |
          npm install cypress
          cd frontend/app
          npm install
          npm run build
          npm run start &
          sleep 120
          cd ..
          cd ..
          npx cypress run

