name: Cypress Tests
on: [push]
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.5.0
      - name: Set up Python 3.10.4
        uses: actions/setup-python@v2
        with:
          python-version: 3.10.4
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip3 install uvicorn
          pip3 install fastapi
          pip3 install supabase
          pip3 install pyyaml
      - name: Run server in background
        run: python3 -m uvicorn backend.main:app &
      - name: Setup Node.js environment
        uses: actions/setup-node@v3.5.1
      - name: Build and run Svelte app
        run: |
          cd frontend/app
          npm install
          npm install cypress
            
      - name: Cypress.io
        uses: cypress-io/github-action@v4.2.0
        with:
          build: |
            /frontend/app
          start: npm --prefix /frontend/app run start &
          config-file: frontend/app/cypress.config.js
          wait-on: 'http://localhost:3400'
